version: "3.3"

services:
  mysql:
    container_name: local_design_note_mysql
    image: mysql:latest
    environment:
      MYSQL_DATABASE: design_note
      MYSQL_ROOT_PASSWORD: password
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      # sql読み込み
      - ./docker/mysql/initdb.d:/docker-entrypoint-initdb.d
      # mysqlの設定を反映する
      - ./docker/mysql/conf.d:/etc/mysql/conf.d
    ports:
      - 3306:3306
